- job:
    description: |
      Test that zuul-operator works in Kubernetes (currently debugging use)
    name: zuul-operator-functional-k8s
    pre-run: playbooks/zuul-operator-functional-k8s/pre.yaml
    run: playbooks/zuul-operator-functional-k8s/run.yaml
    post-run: playbooks/zuul-operator-functional-k8s/post.yaml
    nodeset: ubuntu-xenial
    required-projects:
      - zuul/zuul-operator

- job:
    description: |
      Build's Zuul operator image taken from buildset registry
    name: zuul-operator-build-image
    parent: opendev-build-docker-image
    allowed-projects: zuul/zuul-operator
    vars:
      zuul_work_dir: "{{ zuul.projects['opendev.org/zuul/zuul-operator'].src_dir }}"
      docker_images:
        - context: .
          dockerfile: build/Dockerfile
          repository: zuul/zuul-operator

- job:
    description: |
      Test that zuul-operator works in Openshift (currently debugging use)
    name: zuul-operator-functional-openshift
    # pre-run: playbooks/zuul-operator-functional-openshift/pre.yaml
    run: playbooks/zuul-operator-functional-openshift/run.yaml
    nodeset:
      nodes:
        - name: controller
          label: fedora-29
    required-projects:
      - zuul/zuul-operator

- project:
    check:
      jobs:
        - zuul-operator-build-image
        - zuul-operator-functional-openshift:
            dependencies: zuul-operator-build-image
        # - zuul-operator-build-image
        #- zuul-operator-functional-k8s
            # dependencies: zuul-operator-build-image
    gate:
      jobs:
        - zuul-operator-build-image
        - zuul-operator-functional-openshift:
            dependencies: zuul-operator-build-image
        # - zuul-operator-build-image
        #- zuul-operator-functional-k8s
            # dependencies: zuul-operator-build-image
