- name: start kubernetes and install all dependencies
  hosts: all

  roles:
    - role: bindep
    - role: clear-firewall
    - role: install-kubernetes
      docker_version: 18.06.1~ce~3-0~ubuntu
    - role: use-buildset-registry